#!/usr/bin/env bash
# Binary size (ARCHITECTURE.md §11): ONE row — the stripped release `iota` binary
# (`cargo build --release`, which ci.sh runs just before this). Prints Markdown to
# stdout; ci.sh redirects it into target/size.md. When `cargo bloat` is installed,
# the per-crate breakdown is appended.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$root"
target_dir="${CARGO_TARGET_DIR:-$root/target}"
bin="$target_dir/release/iota"

human() {
    awk -v b="$1" 'BEGIN { printf "%.2f MiB", b / 1048576 }'
}

file_size() {
    if stat -f %z "$1" >/dev/null 2>&1; then stat -f %z "$1"; else stat -c %s "$1"; fi
}

if [[ ! -x "$bin" ]]; then
    cargo build --release >&2
fi
rust_bytes="$(file_size "$bin")"

echo "# Binary size"
echo
echo "Generated by \`scripts/size.sh\` on $(uname -s)/$(uname -m), $(rustc --version), $(date -u +%Y-%m-%dT%H:%MZ)."
echo "Release profile: opt-level=z, lto=fat, codegen-units=1, panic=abort, strip=true."
echo
echo "One shipped binary carrying everything: every provider, every toolset, MCP, the TUI, token"
echo "accounting, syntax highlighting; rustls + aws-lc-rs TLS."
echo
echo "| binary | bytes | size |"
echo "|---|---:|---:|"
echo "| \`iota\` (release, stripped) | $rust_bytes | $(human "$rust_bytes") |"
echo
echo "The heavy parts are two embedded tables — syntect + two-face's syntax/theme dumps (~1.1 MiB)"
echo "and tiktoken's \`o200k_base\` ranks (~0.78 MiB of zstd in the binary, ~0.87 MiB all told,"
echo "decompressed in-process on the first count); the TUI itself (ratatui + crossterm + the ui and"
echo "repl modules) is ~0.4 MiB."

if cargo bloat --version >/dev/null 2>&1; then
    echo
    echo "## cargo bloat (top 30 crates)"
    echo
    echo '```'
    cargo bloat --release --crates -n 30 2>/dev/null || echo "(cargo bloat failed)"
    echo '```'
fi
