//! The inline goldens runner (WP61): every `=== IN:` of `goldens-inline.txt` through
//! `iota::mathtext::approx_inline`, byte-exact, printing the first mismatch with `|…|` markers.
//!
//! The fixture is the RAW output of the real Go package (`internal/mathtext.ApproxInline`),
//! generated by the T3 reader from a throwaway copy compiled outside the Go tree. It is the
//! byte-for-byte contract: it covers everything the Go tests pin PLUS the untested corners
//! (`\frac12`, bare `[…]`, `\left\|`, nested integrals, scripts on fractions).

use iota::mathtext::approx_inline;

/// One `=== IN: <src>` / `|<want>|` pair of the fixture.
struct Golden {
    /// 1-based line number of the `=== IN:` row, for the failure report.
    line: usize,
    /// The LaTeX input.
    input: String,
    /// The expected `ApproxInline` output.
    want: String,
}

/// Parses `goldens-inline.txt`: strictly alternating `=== IN: <src>` and `|<out>|` rows.
fn goldens() -> Vec<Golden> {
    let body = crate::fixture("goldens-inline.txt");
    let lines: Vec<&str> = body.lines().collect();
    let mut out = Vec::new();
    let mut i = 0;
    while i < lines.len() {
        let head = lines[i];
        let input = head
            .strip_prefix("=== IN: ")
            .unwrap_or_else(|| panic!("line {}: {head:?} is not an `=== IN: ` row", i + 1));
        let body_line = lines
            .get(i + 1)
            .unwrap_or_else(|| panic!("line {}: `=== IN:` with no output row", i + 1));
        let want = body_line
            .strip_prefix('|')
            .and_then(|s| s.strip_suffix('|'))
            .unwrap_or_else(|| panic!("line {}: {body_line:?} is not a |…| row", i + 2));
        out.push(Golden {
            line: i + 1,
            input: input.to_owned(),
            want: want.to_owned(),
        });
        i += 2;
    }
    out
}

/// Every fixture row must round-trip byte-exactly through `approx_inline`. The FIRST mismatch is
/// reported with the input, the expected and the actual text, each fenced in `|…|` so trailing
/// spaces are visible.
#[test]
fn inline_goldens_match_go() {
    let cases = goldens();
    assert!(
        cases.len() >= 137,
        "goldens-inline.txt shrank to {} rows",
        cases.len()
    );
    let mut passed = 0usize;
    for g in &cases {
        let got = approx_inline(&g.input);
        assert!(
            got == g.want,
            "inline golden mismatch at goldens-inline.txt:{}\n  IN:   |{}|\n  want: |{}|\n  got:  |{}|\n  ({passed}/{} rows passed before this one)",
            g.line,
            g.input,
            g.want,
            got,
            cases.len()
        );
        passed += 1;
    }
    assert_eq!(passed, cases.len(), "every golden row must pass");
}

/// `ApproxInline` is a ONE-LINE renderer and never emits a combining mark — asserted over the
/// whole corpus, not just the handful of Go inputs that spell it out (`inline.go:29-34`,
/// `inline_test.go:62,94`).
#[test]
fn inline_goldens_are_single_line_and_mark_free() {
    for g in goldens() {
        let got = approx_inline(&g.input);
        assert!(
            !got.contains('\n'),
            "goldens-inline.txt:{}: {:?} produced a newline",
            g.line,
            g.input
        );
        for c in got.chars() {
            let u = c as u32;
            assert!(
                !(0x0300..=0x036F).contains(&u),
                "goldens-inline.txt:{}: {:?} emitted combining mark U+{u:04X}",
                g.line,
                g.input
            );
        }
    }
}

/// `CleanSource` is `ApproxInline` (delim.go:245-247): the display fallback and the inline path
/// are ONE linear renderer, so every golden holds for both entry points.
#[test]
fn clean_source_is_approx_inline() {
    for g in goldens() {
        assert_eq!(
            iota::mathtext::clean_source(&g.input),
            g.want,
            "goldens-inline.txt:{}: clean_source diverged from approx_inline",
            g.line
        );
    }
}
